springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:postgresql:localhost:5432/week1_sb3_g_pgsql_db
    username: week1_db_user
    password: week1_db_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auti: none #упр схемой на ликвибэйс
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml