springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/week1_sb3_g_pgsql
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auti: none #упр схемой на ликвибэйс
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml